/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.iobridge.realtime;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;

@Kroll.module(name = "RealTime", id = "com.iobridge.realtime")
public class RealTimeModule extends KrollModule {

    private static final String TAG = "realTimeModule";

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
        Log.d(TAG, "inside onAppCreate");
    }

    public static KrollDict throwableToErrorDict(Throwable e) {
        if (e == null) return null;
        KrollDict result = new KrollDict();
        result.put("code", 0); // TODO come up with codes for different types of errors?
        result.put("description", e.getMessage());
        return result;
    }
    
}
